---
title: "IBD"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{IBD}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(brms)
library(compositions)
library(glue)
library(multimedia)
library(patchwork)
library(tidyverse)
library(vroom)
theme_set(theme_bw())
```

### Load and Preprocess Data

```{r}
Sys.setenv("VROOM_CONNECTION_SIZE" = 5e6)
taxa <- read_tsv("https://raw.githubusercontent.com/borenstein-lab/microbiome-metabolome-curated-data/main/data/processed_data/FRANZOSA_IBD_2019/genera.tsv")[, -1]
metabolites <- read_tsv("https://raw.githubusercontent.com/borenstein-lab/microbiome-metabolome-curated-data/main/data/processed_data/FRANZOSA_IBD_2019/mtb.tsv")[, -1]
metadata <- read_tsv("https://github.com/borenstein-lab/microbiome-metabolome-curated-data/raw/main/data/processed_data/FRANZOSA_IBD_2019/metadata.tsv")
```

```{r}
filter_mean <- function(x, threshold = 4) {
  col_means <- colMeans(x)
  x[, col_means > threshold]
}

simplify_tax_names <- function(x) {
  colnames(x) <- colnames(x) |>
    str_extract("g__.*+") |>
    str_replace("g__", "g") |>
    str_remove_all("[[:punct:]]")
  x
}

simplify_metab_names <- function(x) {
  colnames(x) <- colnames(x) |>
    str_remove_all("[[:punct:|NA| |\\.|\\/|\\*|,]]") |>
    str_replace_all("-", "_")
  x
}
```

```{r}
taxa <- clr(taxa) |>
  filter_mean(threshold = 4) |>
  simplify_tax_names()

metabolites <- log(1 + metabolites) |>
  filter_mean(threshold = 9) |>
  simplify_metab_names()
  
combined <- metabolites |>
  bind_cols(taxa, metadata) |>
  mutate(treatment = ifelse(Study.Group == "Control", "control", "treatment")) |>
  as_tibble()

exper <- mediation_data(
  combined, 
  colnames(metabolites),
  "treatment",
  colnames(taxa)
)
```

### Lasso Approach

```{r}
model <- multimedia(exper, glmnet_model(lambda = c(0.1, 0.01), nfolds = 3)) |>
  estimate(exper)
```

```{r}
direct <- direct_effect(model, exper) |>
  group_by(outcome) |>
  summarise(direct_effect = mean(direct_effect)) |>
  slice_max(abs(direct_effect), n = 10) |>
  arrange(direct_effect)

combined |>
  select(any_of(direct$outcome), treatment) |>
  pivot_longer(-treatment, names_to = "feature") |>
  mutate(feature = factor(feature, levels = rev(direct$outcome))) |>
  ggplot() +
  geom_boxplot(aes(value, feature, fill = treatment))
```

```{r}
indirect_sorted <- indirect_pathwise(model, exper) |>
  group_by(outcome, mediator) |>
  summarise(indirect_effect = mean(indirect_effect)) |>
  slice_max(abs(indirect_effect), n = 12) |>
  arrange(mediator, indirect_effect)
```

```{r, fig.width = 12, fig.height = 9}
plot_mediators(indirect_sorted, exper)
```

```{r}
altered <- model |>
  nullify("T->Y") |>
  estimate(exper)

profile <- setup_profile(model, exper@treatments, exper@treatments)
samples <- list(
  real = exper@mediators,
  fitted = sample(model, profile = profile)$mediators,
  altered = sample(altered, profile = profile)$mediators
) |>
  bind_rows(.id = "source") |>
  bind_cols(treatment = rep(exper@treatments$treatment, 3)) |>
  pivot_longer(starts_with("g"))

ggplot(samples) +
  geom_boxplot(aes(value, reorder(name, value), fill = treatment)) +
  facet_wrap(~ source)
```

```{r}
inferences <- bind_rows(
  direct = bootstrap(model, exper, direct_effect) |>
    rename(effect = direct_effect),
  indirect = bootstrap(model, exper, indirect_overall) |>
    rename(effect = indirect_effect),
  .id = "path" 
)

inferences |>
  group_by(path, outcome) |>
  summarise(
    mean = mean(effect),
    lower = quantile(effect, 0.025), 
    upper = quantile(effect, 0.0975)
  ) |>
  group_by(path) |>
  slice_max(abs(mean), n = 10)
```
### Random Forest Approach

```{r}
model <- multimedia(exper, rf_model(num.trees = 100)) |>
  estimate(exper)

indirect_sorted <- indirect_pathwise(model, exper) |>
  group_by(outcome, mediator) |>
  summarise(indirect_effect = mean(indirect_effect)) |>
  filter(abs(indirect_effect) > 0.26) |>
  arrange(mediator, indirect_effect)
```

```{r}
model <- multimedia(exper, rf_model(num.trees = 100))
stats <- bootstrap(model, exper)

stats |> filter(outcome %in% c("C18_eg_Clser_0072", "C18_eg_Clser_0018", "C18_eg_Clser_0121")) |> ggplot() + geom_histogram(aes(direct_effect)) + facet_wrap(~ outcome)

altered <- nullify(model, "T->Y")
reference_null <- bootstrap(altered, exper)
de <- direct_effect(estimate(model, exper), exper)
de |>
  arrange(-abs(direct_effect))
```

### Zero-Inflated Gaussian Approach

First, we return to the original scaling.

```{r}
exper2 <- exper
exper2@outcomes <- exp(exper2@outcomes) - 1
```

```{r}
model <- multimedia(
  exper2,
  brms_model(family = hurdle_lognormal())
) |>
  estimate(exper2)
```

```{r}
indirect <- indirect_pathwise(model)
indirect_sorted <- indirect |>
  group_by(outcome, mediator) |>
  summarise(indirect_effect = mean(indirect_effect)) |>
  arrange(-abs(indirect_effect))
```

```{r, fig.width = 12, fig.height = 9}
plot_mediators(indirect_sorted, exper)
plot_mediators(indirect_sorted[12:24], exper)
```

```{r}
direct0 <- direct_effect(model)
direct <- direct0 |>
  group_by(outcome) |>
  summarise(direct_effect = mean(direct_effect)) |>
  slice_max(abs(direct_effect), n = 10) |>
  arrange(direct_effect)

combined |>
  select(any_of(direct$outcome), treatment) |>
  pivot_longer(-treatment, names_to = "feature") |>
  mutate(feature = factor(feature, levels = direct$outcome)) |>
  ggplot() +
  geom_boxplot(aes(value, feature, fill = treatment))
```
