---
title: "illustration"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{illustration}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  fig.align = "center",
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = FALSE,
  eval = TRUE,
  cache = FALSE,
  dev.args = list(bg = "transparent"),
  out.width = 600
)

knitr::knit_hooks$set(output = multimedia::ansi_aware_handler)
options(crayon.enabled = TRUE)

suppressPackageStartupMessages(library(tidyverse))
options(
  ggplot2.discrete.colour = c("#9491D9", "#F24405", "#3F8C61",  "#8C2E62", "#F2B705", "#11A0D9"),
  ggplot2.discrete.fill = c("#9491D9", "#F24405", "#3F8C61", "#8C2E62", "#F2B705", "#11A0D9"),
  ggplot2.continuous.colour = function(...) scale_color_distiller(palette = "Spectral", ...),
  ggplot2.continuous.fill = function(...) scale_fill_distiller(palette = "Spectral", ...)
)

th <- theme_classic() +
  theme(
    panel.background = element_rect(fill="transparent"),
    strip.background = element_rect(fill="transparent"),
    plot.background = element_rect(fill="transparent", color=NA),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.background = element_rect(fill="transparent"),
    legend.box.background = element_rect(fill="transparent"),
    legend.position = "bottom"
  )

theme_set(th)
```

```{r setup}
library(glue)
library(multimedia)
library(splines)
library(tidyverse)
theme_set(theme_classic())
set.seed(20240108)
```

```{r, echo = FALSE}
matnorm <- \(n, m, ...) matrix(rnorm(n * m, ...), n, m)

#' @examples
#' x <- seq(-2, 2, length.out = 100)
#' f <- spline_fun(sd = 0.3)
#' fx <- f(x)
#' plot(x, fx[, 1])
spline_fun <- function(D = 2, knots = NULL, ...) {
  knots <- seq(-4, 4, length.out = 5)
  h_dim <- ns(1:10, knots = knots, intercept = TRUE)
  B <- matnorm(D, ncol(h_dim))
  
  function(x) {
    H <- ns(x, knots = knots, intercept = TRUE)
    scale(H %*% t(B) + rnorm(nrow(H), ...))
  }
}

plot_exper <- function(fit, profile) {
  pivot_samples(fit, profile) |>
    ggplot() +
    geom_point(aes(mediator, value, col = factor(treatment))) +
    facet_grid(. ~ outcome) +
    theme(legend.position = "bottom")
}

pivot_samples <- function(fit, profile) {
  exper_sample <- sample(fit, profile = profile)
  exper_sample@outcomes |>
    bind_cols(exper_sample@mediators, t_outcome) |>
    pivot_longer(starts_with("outcome"), names_to = "outcome")
}
```


This model has two outcomes and a single mediator. We use random spline
functions for the direct effect.

```{r}
N <- 5e3
tau <- rep(2, 2)

treatment <- rep(c(0, 1), each = N / 2)
mediator <- rnorm(N, 2 * (treatment - 0.5), 2)
f <- spline_fun(sd = 0.2)

y <- f(mediator) + matrix(treatment, ncol = 1) %*% tau
colnames(y) <- glue("outcome_{1:2}")
xy_data <- bind_cols(y, mediator = mediator, treatment = factor(treatment))

xy_long <- list(
  true = pivot_longer(xy_data, starts_with("outcome"), names_to = "outcome")
)
```

```{r}
exper <- mediation_data(xy_data, starts_with("outcome"), "treatment", "mediator")
fit <- multimedia(
    exper,
    outcome_estimator = rf_model(num.trees = 1e3)
  ) |>
  estimate(exper)
```

```{r}
t_mediator <- tibble(treatment = factor(rep(unique(treatment), each = N / 2)))
t_outcome <- tibble(treatment = factor(rep(unique(treatment), each = N / 2)))
profile <- setup_profile(fit, t_mediator, t_outcome)
xy_long[["fitted"]] <- pivot_samples(fit, profile)
```

```{r}
# the true effects are 2, 2 
direct_effect(fit) |>
  effect_summary()

# the true effect is +/- 1.5
indirect_overall(fit) |>
  effect_summary()
```
We can analyze the nullified effects.

```{r}
altered_m <- nullify(fit, "T->M") |>
  estimate(exper)
altered_ty <- nullify(fit, "T->Y") |>
  estimate(exper)

fit_lm <- multimedia(
    exper,
    outcome_estimator = lm_model()
  ) |>
  estimate(exper)

xy_long <- c(
  xy_long,
  list(
    altered_m = pivot_samples(altered_m, profile),
    altered_ty = pivot_samples(altered_ty, profile),
    linear = pivot_samples(fit_lm, profile)
  )
) |>
  bind_rows(.id = "fit_type") |>
  mutate(
    fit_type = case_when(
      fit_type == "linear" ~ "Linear Model",
      fit_type == "true" ~ "Original Data",
      fit_type == "fitted" ~ "RF (Full)",
      fit_type == "altered_ty" ~ "RF (T-\\->Y)",
      fit_type == "altered_m" ~ "RF (T-\\->M)"
    ),
    fit_type = factor(fit_type, levels = c("Original Data", "RF (Full)", "RF (T-\\->M)", "RF (T-\\->Y)", "Linear Model")),
    outcome = case_when(
      outcome == "outcome_1" ~ "Y[1]",
      outcome == "outcome_2" ~ "Y[2]"
    )
  )
```


```{r, fig.width = 8, fig.height = 3}
xy_long |>
  sample_frac(size = 0.1) |>
  ggplot(aes(mediator, col = treatment)) +
  geom_point(aes(y = value), size = 0.4, alpha = 0.9) +
  geom_rug(alpha = 0.99, linewidth = 0.1) +
  facet_grid(outcome ~ fit_type) +
  labs(x = expression("Mediator M"), y = "Outcome", col = "Treatment") +
  theme(
    strip.text = element_text(size = 11),
    axis.title = element_text(size = 14),
    legend.title = element_text(size = 12)
  )
#ggsave("~/Desktop/writing/202304/figure/rf_illustration.png", height = 3, widt = 8)
```

```{r}
bootstraps <- bootstrap(fit, exper, fs = list(direct_effect = direct_effect, indirect_overall = indirect_overall))

ggplot(bootstraps$direct_effect) +
  geom_histogram(aes(direct_effect)) +
  facet_wrap(~ outcome)

ggplot(bootstraps$indirect_overall) +
  geom_histogram(aes(indirect_effect)) +
  facet_wrap(~ outcome)
```
