---
title: "IBD"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{IBD}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ggdist)
library(ggrepel)
library(glue)
library(patchwork)
library(tidyverse)
library(multimedia)
data(mindfulness)
```

```{r}
combined <- bind_cols(
  otu_table(mindfulness),
  data.frame(sample_data(mindfulness))
) |>
  mutate(
    treatment = ifelse(treatment == 0, "Control", "Treatment"),
    treatment = factor(treatment, levels = c("Control", "Treatment")),
    subject = factor(subject)
  )

exper <- mediation_data(
  combined,
  taxa_names(mindfulness),
  "treatment", 
  starts_with("mediator"),
  "subject"
)
```

```{r}
model <- multimedia(exper, lnm_model()) |>
  estimate(exper)
```


```{r}
direct <- direct_effect(model, exper)
direct |>
  group_by(outcome) |>
  summarise(direct_effect = mean(direct_effect)) |>
  arrange(-abs(direct_effect))
```

```{r, fig.width = 8, fig.height = 3}
combined |>
  select(starts_with("mediator"), treatment) |>
  pivot_longer(-treatment, names_to = "mediator") |>
  ggplot() +
  geom_boxplot(aes(value, mediator, fill = treatment))
```
```{r}
indirect <- indirect_pathwise(model, exper) |>
  mutate(indirect_effect = -indirect_effect) |> # treatment - control
  arrange(-abs(indirect_effect))  |>
  select(outcome, mediator, indirect_effect)
```

```{r, fig.width = 12, fig.height = 6}
p <- list()
exper_rela < exper
exper_rela@outcome <- exper@outcome / rowSums(exper@outcome)
plot_mediators(indirect, exper_rela)
```

```{r}
altered <- model |>
  nullify("T->M") |>
  estimate(exper)
```

```{r fig.width = 10, fig.height = 4}
new_assign <- exper@treatments[sample(nrow(exper@treatments)), ]
profile <- setup_profile(model, new_assign, new_assign)
m1 <- sample(model, profile = profile, pretreatment = exper@pretreatments)
m2 <- sample(altered, profile = profile, pretreatment = exper@pretreatments)

list(
  real = bind_cols(exper@treatments, exper@mediators, exper@pretreatments),
  original = bind_cols(new_assign, m1$mediators, exper@pretreatments),
  altered = bind_cols(new_assign, m2$mediators, exper@pretreatments)
) |>
  bind_rows(.id = "source") |>
  pivot_longer(starts_with("mediator"), names_to = "mediator") |>
  ggplot() +
  geom_boxplot(aes(value, reorder(mediator, value, median), fill = treatment)) +
  facet_grid(~ source)
```

```{r}
altered_direct <- model |>
  nullify("T->Y") |>
  estimate(exper)

y1 <- sample(model, profile = profile, pretreatment = exper@pretreatments)
y2 <- sample(altered_direct, profile = profile, pretreatment = exper@pretreatments)

names(y1$outcomes) <- names(exper@outcomes)
names(y2$outcomes) <- names(exper@outcomes)
```


```{r, fig.width = 8, fig.height = 12}
list(
  original = bind_cols(exper@treatments, exper@outcomes / rowSums(exper@outcomes)),
  fitted = bind_cols(exper@treatments, y1$outcomes / rowSums(y1$outcomes)),
  altered = bind_cols(exper@treatments, y2$outcomes / rowSums(y2$outcomes))
) |>
  bind_rows(.id = "source") |>
  pivot_longer(-source:-treatment) |>
  ggplot() +
  geom_boxplot(aes(value, reorder(name, value), fill = treatment)) +
  scale_x_log10() +
  facet_grid(~ source)
```

```{r}
contrast <- null_contrast(model, exper, "T->Y", direct_effect)
fdr <- fdr_summary(contrast, "direct_effect", 0.05)
ggplot(fdr, aes(direct_effect, fdr_hat)) +
  geom_label_repel(data = filter(fdr, keep), aes(label = outcome, fill = source), max.overlaps = 25, size = 3) +
  geom_point(aes(col = source)) +
  ylim(-0.1, 0.2) +
  xlim(-0.3, 0.05)

ggplot(fdr, aes(direct_effect, fdr_hat)) +
  geom_label_repel(data = filter(fdr, keep), aes(label = outcome, fill = source), max.overlaps = 50, size = 3, force = 10) +
  geom_point(aes(col = source)) +
  ylim(-0.1, 0.2) +
  xlim(0.0, 0.05)
```


```{r}
contrast <- null_contrast(model, exper, "M->Y", indirect_overall)
fdr <- fdr_summary(contrast, "indirect_overall")

ggplot(fdr, aes(indirect_effect, fdr_hat)) +
  geom_point(aes(col = source)) +
  geom_label_repel(data = filter(fdr, keep), aes(label = outcome, fill = source), force = 20, size = 3)
```

```{r, fig.width = 12, fig.height = 5}
contrast <- null_contrast(model, exper, "M->Y", indirect_pathwise)
fdr <- fdr_summary(contrast, "indirect_pathwise", 0.05)

ggplot(fdr, aes(indirect_effect, fdr_hat)) +
  geom_point(aes(col = source)) +
  geom_label_repel(data = filter(fdr, keep), aes(label = outcome, fill = source), max.overlaps = 50, size = 4) +
  ylim(-0.1, 0.3) +
  facet_wrap(~ mediator)
```

### Random Forest Model

```{r}
exper@outcomes <- log(1 + exper@outcomes)
model <- multimedia(exper, rf_model()) |>
  estimate(exper)

de <- direct_effect(model, exper)

de |>
  group_by(outcome, contrast) |>
  summarise(direct_effect = mean(direct_effect)) |>
  arrange(-abs(direct_effect))

ggplot(combined) +
  geom_boxplot(aes(treatment, log(1 + Akkermansia)))

ie <- indirect_pathwise(model, exper) |>
  group_by(outcome, mediator, contrst) |>
  summarise(indirect_effect = mean(indirect_effect)) |>
  arrange(-abs(indirect_effect))

ie

ggplot(combined) +
  geom_point(aes(mediator.Cold.cereal, log(1 + Lactobacillus), col = treatment))
```

